const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const Doctor = require("./models/Doctor");
require("dotenv").config();

const doctors = [
  {
    name: "Dr. Arun Kumar",
    specialization: "Cardiology",
    bio: "Expert in heart diseases",
    experience: 15,
    rating: 4.8,
    reviews: 342,
    hospital: "Apollo Hospital",
    degrees: ["MD", "MCh Cardiology"],
    fees: 500,
  },
  {
    name: "Dr. Priya Sharma",
    specialization: "Dermatology",
    bio: "Specialist in skin care",
    experience: 12,
    rating: 4.7,
    reviews: 287,
    hospital: "Max Healthcare",
    degrees: ["MD", "Diploma Dermatology"],
    fees: 400,
  },
  {
    name: "Dr. Rajesh Singh",
    specialization: "Orthopedics",
    bio: "Bone and joint specialist",
    experience: 18,
    rating: 4.9,
    reviews: 451,
    hospital: "Fortis Hospital",
    degrees: ["MS Orthopedics", "MCh Sports Medicine"],
    fees: 600,
  },
  {
    name: "Dr. Neha Verma",
    specialization: "Pediatrics",
    bio: "Child health expert",
    experience: 10,
    rating: 4.6,
    reviews: 218,
    hospital: "Artemis Hospital",
    degrees: ["MD", "Diploma Pediatrics"],
    fees: 350,
  },
  {
    name: "Dr. Vikram Patel",
    specialization: "Neurology",
    bio: "Brain specialist",
    experience: 14,
    rating: 4.8,
    reviews: 326,
    hospital: "BLK Hospital",
    degrees: ["DM Neurology", "MD"],
    fees: 700,
  },
  {
    name: "Dr. Anjali Gupta",
    specialization: "Psychiatry",
    bio: "Mental health therapist",
    experience: 11,
    rating: 4.5,
    reviews: 195,
    hospital: "Saket City Hospital",
    degrees: ["DPM", "MD Psychiatry"],
    fees: 450,
  },
  {
    name: "Dr. Arjun Reddy",
    specialization: "General Surgery",
    bio: "Surgical expert",
    experience: 16,
    rating: 4.7,
    reviews: 298,
    hospital: "Apollo Hospital",
    degrees: ["MS General Surgery"],
    fees: 550,
  },
  {
    name: "Dr. Divya Iyer",
    specialization: "Gynecology",
    bio: "Women's health specialist",
    experience: 13,
    rating: 4.8,
    reviews: 367,
    hospital: "Max Healthcare",
    degrees: ["MD", "DGO"],
    fees: 450,
  },
  {
    name: "Dr. Sanjay Malhotra",
    specialization: "Urology",
    bio: "Urinary tract specialist",
    experience: 12,
    rating: 4.6,
    reviews: 241,
    hospital: "Fortis Hospital",
    degrees: ["MS Urology", "MCh Urology"],
    fees: 500,
  },
  {
    name: "Dr. Kavya Desai",
    specialization: "Ophthalmology",
    bio: "Eye care specialist",
    experience: 10,
    rating: 4.7,
    reviews: 289,
    hospital: "Artemis Hospital",
    degrees: ["MS Ophthalmology"],
    fees: 400,
  },
  {
    name: "Dr. Nitin Sharma",
    specialization: "ENT",
    bio: "Ear, nose, throat expert",
    experience: 11,
    rating: 4.5,
    reviews: 206,
    hospital: "BLK Hospital",
    degrees: ["MS ENT"],
    fees: 350,
  },
  {
    name: "Dr. Pooja Singh",
    specialization: "Oncology",
    bio: "Cancer care specialist",
    experience: 14,
    rating: 4.9,
    reviews: 412,
    hospital: "Saket City Hospital",
    degrees: ["DM Oncology", "MD"],
    fees: 800,
  },
  {
    name: "Dr. Harsh Verma",
    specialization: "Pulmonology",
    bio: "Respiratory specialist",
    experience: 12,
    rating: 4.7,
    reviews: 273,
    hospital: "Apollo Hospital",
    degrees: ["DM Pulmonology", "MD"],
    fees: 480,
  },
  {
    name: "Dr. Sneha Kapoor",
    specialization: "Rheumatology",
    bio: "Joint disease specialist",
    experience: 10,
    rating: 4.6,
    reviews: 198,
    hospital: "Max Healthcare",
    degrees: ["DM Rheumatology", "MD"],
    fees: 500,
  },
  {
    name: "Dr. Rohan Gupta",
    specialization: "Gastroenterology",
    bio: "Digestive system expert",
    experience: 13,
    rating: 4.8,
    reviews: 334,
    hospital: "Fortis Hospital",
    degrees: ["DM Gastroenterology", "MD"],
    fees: 550,
  },
  {
    name: "Dr. Rupali Nair",
    specialization: "Nephrology",
    bio: "Kidney specialist",
    experience: 11,
    rating: 4.7,
    reviews: 267,
    hospital: "Artemis Hospital",
    degrees: ["DM Nephrology", "MD"],
    fees: 500,
  },
  {
    name: "Dr. Aman Chopra",
    specialization: "Endocrinology",
    bio: "Hormone specialist",
    experience: 10,
    rating: 4.5,
    reviews: 214,
    hospital: "BLK Hospital",
    degrees: ["DM Endocrinology", "MD"],
    fees: 480,
  },
  {
    name: "Dr. Meera Bhat",
    specialization: "Hematology",
    bio: "Blood disorder specialist",
    experience: 12,
    rating: 4.6,
    reviews: 245,
    hospital: "Saket City Hospital",
    degrees: ["DM Hematology", "MD"],
    fees: 520,
  },
  {
    name: "Dr. Siddharth Kumar",
    specialization: "Infectious Diseases",
    bio: "Infection specialist",
    experience: 11,
    rating: 4.7,
    reviews: 276,
    hospital: "Apollo Hospital",
    degrees: ["DM Infectious Diseases", "MD"],
    fees: 490,
  },
  {
    name: "Dr. Ananya Rao",
    specialization: "Immunology",
    bio: "Immune system expert",
    experience: 10,
    rating: 4.5,
    reviews: 187,
    hospital: "Max Healthcare",
    degrees: ["DM Immunology", "MD"],
    fees: 450,
  },
  {
    name: "Dr. Varun Nath",
    specialization: "Cardiology",
    bio: "Cardiac interventionist",
    experience: 15,
    rating: 4.8,
    reviews: 389,
    hospital: "Fortis Hospital",
    degrees: ["DM Cardiology", "MD"],
    fees: 650,
  },
  {
    name: "Dr. Ishita Jain",
    specialization: "Radiation Oncology",
    bio: "Cancer radiation expert",
    experience: 12,
    rating: 4.7,
    reviews: 298,
    hospital: "Artemis Hospital",
    degrees: ["MD Radiotherapy"],
    fees: 700,
  },
  {
    name: "Dr. Nikhil Reddy",
    specialization: "Vascular Surgery",
    bio: "Blood vessel specialist",
    experience: 13,
    rating: 4.6,
    reviews: 256,
    hospital: "BLK Hospital",
    degrees: ["MCh Vascular Surgery"],
    fees: 600,
  },
  {
    name: "Dr. Simran Kumar",
    specialization: "Emergency Medicine",
    bio: "Critical care expert",
    experience: 10,
    rating: 4.5,
    reviews: 234,
    hospital: "Saket City Hospital",
    degrees: ["MD Emergency Medicine"],
    fees: 400,
  },
  {
    name: "Dr. Aditya Singh",
    specialization: "Radiology",
    bio: "Imaging specialist",
    experience: 11,
    rating: 4.7,
    reviews: 289,
    hospital: "Apollo Hospital",
    degrees: ["MD Radiology", "DMRE"],
    fees: 350,
  },
  {
    name: "Dr. Shruti Patel",
    specialization: "Anesthesiology",
    bio: "Anesthesia expert",
    experience: 12,
    rating: 4.6,
    reviews: 267,
    hospital: "Max Healthcare",
    degrees: ["MD Anesthesia"],
    fees: 400,
  },
  {
    name: "Dr. Pranav Verma",
    specialization: "Pathology",
    bio: "Lab diagnostics expert",
    experience: 10,
    rating: 4.5,
    reviews: 201,
    hospital: "Fortis Hospital",
    degrees: ["MD Pathology"],
    fees: 300,
  },
  {
    name: "Dr. Akshara Nair",
    specialization: "Microbiology",
    bio: "Infection testing expert",
    experience: 9,
    rating: 4.4,
    reviews: 178,
    hospital: "Artemis Hospital",
    degrees: ["MD Microbiology"],
    fees: 280,
  },
  {
    name: "Dr. Ravi Kant",
    specialization: "Dentistry",
    bio: "Oral health expert",
    experience: 11,
    rating: 4.7,
    reviews: 312,
    hospital: "BLK Hospital",
    degrees: ["BDS", "MDS"],
    fees: 300,
  },
  {
    name: "Dr. Amina Khan",
    specialization: "Orthopedics",
    bio: "Joint replacement specialist",
    experience: 14,
    rating: 4.8,
    reviews: 378,
    hospital: "Saket City Hospital",
    degrees: ["MS Orthopedics", "MCh"],
    fees: 650,
  },
  {
    name: "Dr. Ravi Kumar",
    specialization: "Plastic Surgery",
    bio: "Cosmetic surgeon",
    experience: 12,
    rating: 4.7,
    reviews: 289,
    hospital: "Apollo Hospital",
    degrees: ["MS Plastic Surgery"],
    fees: 1000,
  },
  {
    name: "Dr. Swati Chatterjee",
    specialization: "Psychiatry",
    bio: "Depression specialist",
    experience: 11,
    rating: 4.6,
    reviews: 245,
    hospital: "Max Healthcare",
    degrees: ["MD Psychiatry", "DPM"],
    fees: 500,
  },
  {
    name: "Dr. Mohan Reddy",
    specialization: "Ophthalmology",
    bio: "Cataract specialist",
    experience: 13,
    rating: 4.8,
    reviews: 356,
    hospital: "Fortis Hospital",
    degrees: ["MS Ophthalmology"],
    fees: 450,
  },
  {
    name: "Dr. Priyanka Saxena",
    specialization: "Dermatology",
    bio: "Acne specialist",
    experience: 10,
    rating: 4.6,
    reviews: 267,
    hospital: "Artemis Hospital",
    degrees: ["MD Dermatology"],
    fees: 400,
  },
  {
    name: "Dr. Sandeep Malhotra",
    specialization: "General Medicine",
    bio: "Internal medicine expert",
    experience: 14,
    rating: 4.7,
    reviews: 301,
    hospital: "BLK Hospital",
    degrees: ["MD General Medicine"],
    fees: 400,
  },
  {
    name: "Dr. Geeta Verma",
    specialization: "Pediatrics",
    bio: "Vaccination expert",
    experience: 11,
    rating: 4.7,
    reviews: 298,
    hospital: "Saket City Hospital",
    degrees: ["MD Pediatrics"],
    fees: 350,
  },
  {
    name: "Dr. Arjun Desai",
    specialization: "Cardiology",
    bio: "Arrhythmia specialist",
    experience: 15,
    rating: 4.9,
    reviews: 423,
    hospital: "Apollo Hospital",
    degrees: ["DM Cardiology"],
    fees: 700,
  },
  {
    name: "Dr. Nisha Yadav",
    specialization: "Gynecology",
    bio: "High-risk pregnancy",
    experience: 13,
    rating: 4.8,
    reviews: 347,
    hospital: "Max Healthcare",
    degrees: ["MD Obstetrics"],
    fees: 500,
  },
  {
    name: "Dr. Vikram Gupta",
    specialization: "Neurosurgery",
    bio: "Brain surgery expert",
    experience: 16,
    rating: 4.9,
    reviews: 395,
    hospital: "Fortis Hospital",
    degrees: ["MCh Neurosurgery"],
    fees: 1200,
  },
  {
    name: "Dr. Divya Kapoor",
    specialization: "Pulmonology",
    bio: "Asthma specialist",
    experience: 10,
    rating: 4.6,
    reviews: 234,
    hospital: "Artemis Hospital",
    degrees: ["MD Pulmonology"],
    fees: 450,
  },
  {
    name: "Dr. Clement D'Souza",
    specialization: "Urology",
    bio: "Prostate specialist",
    experience: 12,
    rating: 4.7,
    reviews: 289,
    hospital: "BLK Hospital",
    degrees: ["MS Urology"],
    fees: 500,
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    // Clear existing doctors
    await Doctor.deleteMany({});
    console.log("Cleared existing doctors");

    // Hash passwords and insert doctors
    const doctorsWithPasswords = await Promise.all(
      doctors.map(async (doctor) => {
        const hash = await bcrypt.hash("doctor123", 10);
        const generatedEmail = `${doctor.name
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, ".")
          .replace(/^\.+|\.+$/g, "")}@hospital.com`;

        return {
          ...doctor,
          email: doctor.email || generatedEmail,
          password: hash,
        };
      }),
    );

    await Doctor.insertMany(doctorsWithPasswords);
    console.log(`Inserted ${doctors.length} doctors successfully`);

    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
};

seedDatabase();
